project:
  type: website
  resources:
    - papers/*.pdf
    - resume.pdf
    - profile.jpg

website:
  title: "Victoria Vivian Chan"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: experience.qmd
        text: Experience
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
    right:
      - href: resume.pdf
        text: Resume

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">